# Generated by Django 4.2.13 on [your-migration-date]

from django.db import migrations, models
import uuid

class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('session_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('django_session_key', models.CharField(max_length=40, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'sessions',
                'app_label': 'rag',
            },
        ),
        migrations.CreateModel(
            name='Pdf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('pdf_hash', models.CharField(max_length=64)),
                ('session', models.ForeignKey(on_delete=models.CASCADE, to='rag.session')),
            ],
            options={
                'db_table': 'pdfs',
                'app_label': 'rag',
            },
        ),
        migrations.CreateModel(
            name='ConversationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=models.CASCADE, to='rag.session')),
            ],
            options={
                'db_table': 'conversation_history',
                'app_label': 'rag',
            },
        ),
    ]
